

export const ADD_CATEGORY = "ADD_CATEGORY";
export const LOAD_CATEGORY = "LOAD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const LOAD_SINGLE_CATEGORY = "LOAD_SINGLE_CATEGORY"
export const ADD_BLOG = "ADD_BLOG"
export const LOAD_BLOG = "LOAD_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const ALL_POST = "ALL_POST"
export const YOUR_POST = "YOUR_POST"
export const FILTER_CATEGORY = "FILTER_CATEGORY"